### PR TITLE
Add the ‘sqrt’ code.

### PR DESCRIPTION
**Pull request by PankajGacche**

### CODE REVIEW

**Review by AutomationTestEngineer1 — CHANGES_REQUESTED** [review]
Give proper name to sqrt function.

**Review by PankajGacche — COMMENTED** [review]
As per suggestion made changes in sqrt function name, please approve my pull request.

**Review by AutomationTestEngineer1 — APPROVED** [review]
Now sqrt function name looks good. Pull request Approved.

**Comment by PankajGacche** [comment]
Got approval from reviewer to merge this request.

**Pull request merged**
